CREATE TABLE "ski_resorts" (
	"id" varchar(128) PRIMARY KEY NOT NULL,
	"name" varchar(512) NOT NULL,
	"country" varchar(128),
	"region" varchar(256),
	"locality" varchar(256),
	"status" varchar(64) DEFAULT 'unknown' NOT NULL,
	"has_downhill" boolean,
	"has_nordic" boolean,
	"downhill_distance_km" double precision,
	"nordic_distance_km" double precision,
	"vertical_m" integer,
	"min_elevation_m" integer,
	"max_elevation_m" integer,
	"lift_count" integer,
	"surface_lifts_count" integer,
	"run_convention" varchar(64),
	"wikidata_id" varchar(64),
	"websites" text,
	"openskimap_url" varchar(1024) NOT NULL,
	"geometry" varchar(64) NOT NULL,
	"latitude" double precision NOT NULL,
	"longitude" double precision NOT NULL,
	"sources" text,
	"imported_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
